/** 数独配色 */

export const SU_PAGE_BG: string = '#0A0A0A';
export const SU_BOARD_BG: string = '#0D1117';
/** 普通格子背景 */
export const SU_CELL_BG: string = '#161B22';
/** 选中格子背景 */
export const SU_CELL_SELECTED: string = '#1A3D1A';
/** 同行/列/宫高亮 */
export const SU_CELL_HIGHLIGHT: string = '#111D11';
/** 冲突格子背景 */
export const SU_CELL_CONFLICT: string = '#331111';
/** 初始数字颜色 */
export const SU_FIXED_COLOR: string = '#00FFFF';
/** 用户输入颜色 */
export const SU_INPUT_COLOR: string = '#00FF41';
/** 笔记颜色 */
export const SU_NOTE_COLOR: string = '#39D353';
/** 宫格分隔线颜色 */
export const SU_BOX_BORDER: string = '#00FF4166';
/** 普通分隔线 */
export const SU_CELL_BORDER: string = '#00FF4118';
